			<div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Dashboard</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
			<div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary" id="members-dashboard">
                        
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-green" id="services-dashboard">
                        
                       
                    </div>
                </div>
                            
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-yellow" id="users-dashboard">
                        
                    </div>
                </div>
                            
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-red" id="clients-dashboard">
                        
                </div>
            </div>


<script>
<?php $this->inlineScript()->captureStart(); ?>
    
            //ajax zahtev
            //members
        $.ajax({
            url: '<?php echo $this->url(array('controller' => 'admin_members', 'action' => 'dashboard'), 'default', true);?>',
            cashe: false
    
    
        }).done(function(data) {
                $('#members-dashboard').append(data);
             
                
        }).fail(function() {
            //znaci da li je doslo do greske sa serverom// neuspesna komunikacija sa serverom
            alert('Unable to load members');
            
        }).always(function() {
            
        });
        
        //services
        $.ajax({
            url: '<?php echo $this->url(array('controller' => 'admin_services', 'action' => 'dashboard'), 'default', true);?>',
            cashe: false
    
    
        }).done(function(data) {
                $('#services-dashboard').append(data);
             
                
        }).fail(function() {
            //znaci da li je doslo do greske sa serverom// neuspesna komunikacija sa serverom
            alert('Unable to load services');
            
        }).always(function() {
            
        });
        
        
         //users
        $.ajax({
            url: '<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'dashboard'), 'default', true);?>',
            cashe: false
    
    
        }).done(function(data) {
                $('#users-dashboard').append(data);
             
                
        }).fail(function() {
            //znaci da li je doslo do greske sa serverom// neuspesna komunikacija sa serverom
            alert('Unable to load users');
            
        }).always(function() {
            
        });
        
         //clients
        $.ajax({
            url: '<?php echo $this->url(array('controller' => 'admin_clients', 'action' => 'dashboard'), 'default', true);?>',
            cashe: false
    
    
        }).done(function(data) {
                $('#clients-dashboard').append(data);
             
                
        }).fail(function() {
            //znaci da li je doslo do greske sa serverom// neuspesna komunikacija sa serverom
            alert('Unable to load clients');
            
        }).always(function() {
            
        });
        
        
        
    
<?php $this->inlineScript()->captureEnd(); ?>
</script> 