<?php 
//disable-vovanje layouta
Zend_Layout::getMvcInstance()->disableLayout();

?>
<!DOCTYPE html>
<html>
<head></head>
<body>
	<h1>Choose your car brand/model</h1>
	<form action="" method="post">
		<p>
		<label>Brand</label>
		<select id="car-brand">
			<option value="">--- Choose Brand ---</option>
                        
		</select>
		</p>
		<p>
		<label>Model</label>
		<select id="car-model">
			<option value="">--- Choose Model ---</option>
		</select>
		</p>
	</form>
        
        <script src="<?php echo $this->baseUrl('/admin/bower_components/jquery/dist/jquery.min.js');?>"></script>
        <script>
        $('#car-brand').on('change', function(e){
            
            //e.preventDefault();
            e.stopPropagation();
            
            var target = $(this).is('#car-brand') ? $(this) : $(this).closest('#car-brand');
            
            //selektujemo vrednost
            var brand = target.val();
            //praznimo -reset
            var modelSelect = $('#car-model');
            
            //clear element inner html
            modelSelect.empty();
            
            modelSelect.append('<option value="">--- Choose Model ---</option>');
           
           if (brand) {
               $.ajax({
                   //url do akcije controlera
                   url: '<?php echo $this->url(array('controller' => 'admin_test', 'action' => 'ajaxmodels'), 'default', true);?>',
                   //data je kljuc koji je objekat, prosledjivanje parametara koje prosledjujemo na url:
                   //data je prazan po difoltu
                   data:{
                       "brand": brand
                   },
                           //method je po difoltu get ako se na navede
                   method: "post",
                   //nemoj da mi kesiras odgovor dohvati mi najsveziju informaciju
                   cashe: false
                   
               }).done(function(data){
                   
                   for(var index in data) {
                       
                       var model = data[index];
                       
                       var selectOption = $('<option></option>');
                       
                       selectOption.attr('value', model.value);
                       //ako hocemo tekst onda u mesto .html stavimo .text
                       //prikazuje html tagove
                       //selectOption.html(model.label);
                       //ono stro tretiramo prikazujemo kao tekst
                       selectOption.text(model.label);
                       
                       modelSelect.append(selectOption);
                   }
                   
                   
               }).fail(function() {
                   
                   alert('Unable to load models for brand');
                   
               }).always(function () {
                   
               });
           }
        });
        
        
        
        
        //slanje jQuery zahteva
       // $.ajax('test/html', {});
        //ovaj php se izvrsava u browseru
        $.ajax({
            url: '<?php echo $this->url(array('controller' => 'admin_test', 'action' => 'ajaxbrands'), 'default', true);?>',
            cash: false
        //jqXHR - AJAX zahtev// data (string koji cuva html)- telo odgovora koje dolazi prilikom zahteva sa servera
        }).done(function(data, textStatus, jqXHR) {
            //on successfull ajax page load - uspesno ucitana stranica
            for(var index in data){
                
                var brand = data[index];
                // jquery f-ja za html
                var selectOption = $('<option></option>')
                
                selectOption.attr('value', brand.value);
                selectOption.html(brand.label);
                
                $('#car-brand').append(selectOption);
            }
            
            
        }).fail(function( jqXHR, textStatus, errorThrown ) {
            //on error while loading ajax page
            alert ('Error occured while loading car brands');
        }).always(function() {
            //for action that do not depend on result
        });
        
        
        </script>
</body>
</html>
