<?php
$this->headTitle('Profile - Change Password');
?>

<div class="page-header">
    <h1>Profile  <small>Change Password </small></h1>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right">
                <div class="btn-group" role="group" aria-label="...">
                    <a 
                        href="<?php echo $this->url(array('controller' => 'admin_profile', 'action' => 'edit'), 'default', true); ?>" type="button" 
                        class="btn btn-default"
                        ><i class="fa fa-user"></i>Change password</a>
                </div>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="post" action="">
                    <fieldset>


                        <!-- Form Name -->
                        <legend>Form Name</legend>

                        <!-- Password input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="new_password">New Password</label>
                            <div class="col-md-4">
                                <input id="new_password" name="new_password" placeholder="enter new password" class="form-control input-md" required="" type="password">
                                <span class="help-block">min 5 max 255 characters</span>
                            </div>
                        </div>

                        <!-- Password input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="new_password_confirm">Confirm new password</label>
                            <div class="col-md-4">
                                <input id="new_password_confirm" name="new_password_confirm" placeholder="confirm new password" class="form-control input-md" required="" type="password">
                                <span class="help-block">min 5 max 255 characters</span>
                            </div>
                        </div>

                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
